name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build:all:dev:once

      - name: Ensure test-results dir exists
        run: mkdir -p test-results

      - name: Run E2E tests
        env:
          ELECTRON_TEST_MODE: 'true'
          CI: 'true'
          ELECTRON_DISABLE_SANDBOX: 'true'
        run: npm run test:e2e:ci

      - name: Upload test results (JUnit XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-junit-xml
          path: test-results/junit.xml
          retention-days: 7
          if-no-files-found: ignore
          fail_on_failure: false

      - name: Publish test report (if supported)
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'test-results/junit.xml'
          check_name: 'End-to-End Test Results'
          fail_on_failure: true
          require_tests: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            test-results/
            /tmp/e2e-*.log
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload Electron logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: electron-logs
          path: /tmp/e2e-electron.log
          retention-days: 7
          if-no-files-found: ignore
