name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install dependencies
        run: npm ci

      - name: Build and run E2E
        env:
          ELECTRON_TEST_MODE: 'true'
        run: npm run test:e2e:ci

      - name: Upload Electron log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-electron-log
          path: /tmp/e2e-electron.log

